name: Test

on:
  push:
    branches:
      - "main"
    paths:
      - "test/**"

  workflow_dispatch:

  schedule:
    - cron: "0 1 * * *"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: latest
      - run: yarn
      - run: yarn test
