name: Test

on:
  # push:
  #   branches:
  #     - "main"

  # pull_request:

  workflow_dispatch:

#   schedule:
#     - cron: "0 6 * * 3"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: true

      - uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: "pnpm"

      - run: pnpm build && pnpm test
