name: Test

on:
  push:
    branches:
      - "main"

  pull_request:

  workflow_dispatch:

#   schedule:
#     - cron: "0 6 * * 3"

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: false

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Run test
        run: pnpm test
